### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by AladdinT** [arhassan98/Embedded-Linux#1] opened 2023-09-02 11:50 UTC
Pros : Very Organized , Perfect coding.
Cons : 
> Writing python as c style 
> Only session 1 tasks were uploaded 
> Nice and tidy readme , but if it is time consuming, I'd prefer all tasks done instead

**Comment by arhassan98** [comment] 2023-09-08 21:03
Dear Eng. Ahmad Tohamy,

Thank you for reviewing my uploaded tasks on GitHub. I appreciate your positive feedback on organization and coding quality. I apologize for only uploading the tasks from session 1 and for any confusion caused by writing Python in a C-style manner. Due to unforeseen circumstances, I couldn't complete the remaining tasks within the given time. I will prioritize completing the outstanding tasks and uploading them. I understand your concern about the readme, and I will ensure a balance between maintaining it and completing the tasks. Thank you for your feedback, and I'm committed to delivering better results.

Best regards,
Ahmed Hassan

**Closed by arhassan98** 2023-09-08 21:03 UTC

**Comment by AladdinT** [comment] 2023-09-16 18:29
**UPDATE**
Outstanding Job , keep it up. 
Unique and creative solution for "1- Python/2/7- Parse Header File" , well done.
Yet just two notes:
- Please separate between session 2,and session 3 tasks.
- afew tasks are missing , Missing bitcoin api, fav website, location api,vscode extension installer, Missing mark as read, gpio init.
